# Generated by Django 3.1.1 on 2021-03-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssolutionmodel',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='businesssolutionmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/actus-images/'),
        ),
    ]
