# Generated by Django 3.1.1 on 2021-03-01 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Description')),
                ('gender', models.CharField(blank=True, choices=[('F', 'Féminin'), ('M', 'Masculin')], max_length=1, verbose_name='Genre')),
                ('country', models.CharField(choices=[('RDC', 'Republique Democratique du Congo'), ('RSA', 'Repulic South Africa')], default='+243', max_length=100, verbose_name='Pays')),
                ('birthday', models.DateField(blank=True, verbose_name='Date de naissance')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site Web')),
                ('avatar', models.ImageField(blank=True, upload_to='static/assets/img/users')),
                ('bio', models.TextField(blank=True, null=True)),
                ('cellphone', models.CharField(max_length=15, verbose_name='Téléphone')),
                ('slug', models.SlugField(help_text='Unique value for user page URL, created from name.', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_keywords', models.CharField(help_text='Comma-delimited set of SEO keywords for meta tag', max_length=255, verbose_name='Meta Keywords')),
                ('meta_description', models.CharField(help_text='Content for description meta tag', max_length=255, verbose_name='Meta Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
